export const Items = [
        { name: 'House & DIY' , categoryName: 'houseanddiy', icon: 'home' },
        { name: 'Animals', categoryName: 'animals', icon: 'pets' },
        { name: 'Electronics', categoryName: 'electronics',  icon: 'phonelink' } ,
        { name: 'Sports & Hobbies', categoryName: 'sportsandhobbies', icon: 'accessibility_new' },
        { name: 'Clothes & Lifestyle', categoryName: 'clothesandlifestyle', icon: 'face'},
        { name: 'Farming', categoryName: 'farming', icon: 'spa'},
        { name: 'Baby & Kinds', categoryName: 'babyandkinds', icon: 'child_care'},
        { name: 'Cars & Motor', categoryName: 'carsandmotor', icon: 'drive_eta'},
        { name: 'Business', categoryName: 'business', icon: 'business'},
        { name: 'Holidays & Tickets', categoryName: 'holidaysandtickets', icon: 'beach_access'},
        { name: 'Lost & Found', categoryName: 'lostandfound',  icon: 'sentiment_dissatisfied'},
        { name: 'Music & Education', categoryName: 'musicandeducation', icon: 'music_note'},
        { name: 'Other', categoryName: 'other', icon: 'more'},
        { name: 'Property', categoryName: 'property', icon: 'store'},
        { name: 'Work', categoryName: 'work', icon: 'work'},
      ];
